# Generated by Django 4.0.3 on 2023-01-24 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
    ]
